services:
    _defaults:
        autoconfigure: true

    Doublespark\FaqGeneratorBundle\Controller\BackendGenerateQuestionsController:
        public: true
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - '@twig'